// src/Dto/Proveedor.dto.ts

/**
 * Represents the full data structure of a Proveedor (Supplier) as received from the API.
 */
export interface ProveedorDto {
  id: number;
  nombre: string;
  telefono: string | null;
  direccion: string | null;
  catalogo: string | null;
  createdAt: Date; // Assuming your backend adds timestamps
  updatedAt: Date; // Assuming your backend adds timestamps
}

/**
 * Represents the data required to create a new Proveedor.
 * ID and timestamps are typically generated by the backend.
 */
export interface ProveedorCreateDto {
  nombre: string;
  telefono?: string | null; // Optional, can be null
  direccion?: string | null; // Optional, can be null
  catalogo?: string | null; // Optional, can be null
}

/**
 * Represents the data required to update an existing Proveedor.
 * All fields are optional as you might only update a subset.
 */
export interface ProveedorUpdateDto {
  nombre?: string;
  telefono?: string | null;
  direccion?: string | null;
  catalogo?: string | null;
}
